FROM node:20-bookworm-slim

WORKDIR /home/node/app

COPY package.json pnpm-lock.yaml .npmrc ./

RUN corepack enable && pnpm install --frozen-lockfile

CMD ["sh", "-c", "corepack pnpm dev:bootstrap && corepack pnpm exec next dev --hostname 0.0.0.0"]
